(test
 (name test_mlkem)
 (modes byte exe)
 (libraries alcotest mlkem mlkem.for_testing)
 (deps (glob_files vectors/*.txt)))

(test
 (name test_mldsa)
 (modes byte exe)
 (libraries alcotest mldsa mldsa.for_testing)
 (deps (glob_files mldsa_vectors/*.txt)))

(test
 (name test_slhdsa_hash)
 (modes byte exe)
 (libraries slhdsa.for_testing))

(test
 (name test_slhdsa)
 (modes exe)
 (libraries alcotest slhdsa slhdsa.for_testing)
 (deps (glob_files slhdsa_vectors/*.txt)))

(executable
 (name test_js)
 (modes js)
 (libraries mlkem mldsa slhdsa)
 (enabled_if
  (= %{profile} js)))
