(library
 (name slhdsa)
 (public_name slhdsa)
 (modules
  slhdsa_hash
  slhdsa_engine
  slhdsa
  slhdsa_sha2_128s
  slhdsa_sha2_128f
  slhdsa_sha2_192s
  slhdsa_sha2_192f
  slhdsa_sha2_256s
  slhdsa_sha2_256f
  slhdsa_shake_128s
  slhdsa_shake_128f
  slhdsa_shake_192s
  slhdsa_shake_192f
  slhdsa_shake_256s
  slhdsa_shake_256f))

(library
 (name slhdsa_for_testing)
 (public_name slhdsa.for_testing)
 (modules slhdsa_for_testing)
 (libraries slhdsa))
